  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-service
spec:
  selector:
    matchLabels:
      app: mnist-service
  replicas: 3
  template:
    metadata:
      labels:
        app: mnist-service
    spec:
      containers:
      - name: mnist-service
        image: ashwinpn/hw5_inference
