apiVersion: v1
kind: Pod
metadata:
  name: infer-model
spec:
  containers:
  - name: tensorflow
    image: ashwinpn/hw5_inference
    volumeMounts:
    - name: mnist-train
      mountPath: /trainer-job
  volumes:
  - name: mnist-train
    persistentVolumeClaim:
      claimName: mnist-train
