apiVersion: v1
kind: Pod
metadata:
  name: infer-model
spec:
  containers:
  - name: infer-model
    image: ashwinpn/hw5_inference
    volumeMounts:
    - mountPath: /trainer-job
      name: mnist-train
  volumes:
  - name: mnist-train
    persistentVolumeClaim:
      claimName: mnist-train
