apiVersion: v1
kind: Pod
metadata:
  name: trainer-job
spec:
  containers:
  - name: mnist-training
    image: ashwinpn/hw5
    volumeMounts:
      - mountPath: /trainer-job
        name: mnist-train
  volumes:
    - name: mnist-train
      persistentVolumeClaim:
        claimName: mnist-train
